services:
  servidor-html:
    name: alfonso_svr
    #image: servidor-html
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "C:/Users/Alumnos Tarde/Desktop/Jorge Quiroga/IFCD0210/MF0493/compose_jorge:/data"